### ISSUE TITLE
Can't Enable as Addon or Open Project 

### ISSUE THREAD

**Issue by MadMikeTX** [V-Sekai/unidot_importer#41]
I previously used  unidot importer in conjunction with  (https://github.com/barcoderdev/unitypackage_godot) ---> their version of **FBX2glTF** and it worked fantastically for my game project. However, I had to reinstall my project recently and in turn re-install both FBX2glTF and unidot importer (your updated version). But now I'm getting the error below and can't open my project.

 
*Version of **FBX2glTF** ( https://github.com/barcoderdev/FBX2glTF/actions/runs/7305203107) I used

Trying to figure out where the issue is. Any help would be much appreciated. 

![Screenshot (1)](https://github.com/V-Sekai/unidot_importer/assets/140464060/14482a41-fc73-43a4-96e1-7b4aa366a4f0)
![Screenshot (2)](https://github.com/V-Sekai/unidot_importer/assets/140464060/04bdf09d-27ea-4bbb-b5f8-73ee95525ea7)

**Comment by lyuma** [comment]
Aha, thanks for the report! I had introduced a script error which occurred in Godot 4.1 and earlier. I have fixed the problem on the latest version of this git repository.
I have not yet released this fix or published it to the asset library, so you need to use the git version, either by cloning it or [downloading the latest zip](https://github.com/V-Sekai/unidot_importer/archive/refs/heads/main.zip)

Regarding FBX2glTF, the current recommendation is to download the latest official Godot build from https://github.com/godotengine/FBX2glTF/releases since it contains one additional bugfix not present in barcoder's version. That said, the bugfix is not significant for unidot purposes and either version will likely work.

**Comment by MadMikeTX** [comment]
Thanks so much for getting back to me so soon. I used the zip file and was able to 'enable' unidot as an addon.
I'm still getting errors and I can't re-import anything -- so I'll just wait until you release/publish the fixes.
Either way, thanks for hitting me back. Big fan of the unidot importer.

![Screenshot (3)](https://github.com/V-Sekai/unidot_importer/assets/140464060/2923ba9e-4c04-4a1c-b84c-574d9af95c2a)
![Screenshot (4)](https://github.com/V-Sekai/unidot_importer/assets/140464060/e1fe6eed-45f5-4ce9-bdd0-26ba1de1a4f9)
